### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by sondresorbye** [thiagofeijor/node-link-preview#2]
Your library does not work

const LinkPreview2 = require('node-link-preview')
Error: Cannot find module './link-preview.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Sondr\Desktop\scrumboard\functions\node_modules\node-link-preview\index.js:5:28)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by yogeshnishad** [comment]
try this it worked for me 
https://www.npmjs.com/package/link-preview-node
